;this file for FamiTone2 library generated by text2data tool

wonder_boy_music_data:
	.byte 12
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,307,256

@instruments:
	.byte $f0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c4,$c5,$c6,$c7,$c8,$c7,$c6,$c5,$00,$07
@env2:
	.byte $c8,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06


@song0ch0:
	.byte $fb,$0a
@song0ch0loop:
@ref0:
	.byte $83,$80,$4f,$4d,$4f,$4e,$48,$83,$52,$4e,$83
@ref1:
	.byte $83,$4f,$4d,$4f,$4e,$48,$83,$52,$4e,$83
	.byte $ff,$0a
	.word @ref1
@ref3:
	.byte $4c,$4c,$4c,$4c,$52,$52,$52,$52,$56,$8d
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $83,$80,$3f,$3b,$3f,$3e,$3a,$83,$40,$3e,$83
@ref5:
	.byte $83,$3f,$3b,$3f,$3e,$3a,$83,$40,$3e,$83
@ref6:
	.byte $83,$3f,$3b,$3f,$3e,$3a,$83,$40,$3a,$83
@ref7:
	.byte $81,$3a,$3a,$3a,$40,$40,$40,$40,$3e,$8d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $82,$36,$36,$36,$36,$36,$36,$36,$36,$40,$40,$40,$40,$40,$40,$40
	.byte $40
@ref9:
	.byte $36,$36,$36,$36,$36,$36,$36,$36,$40,$40,$40,$40,$40,$40,$40,$40
	.byte $ff,$10
	.word @ref9
@ref11:
	.byte $44,$44,$44,$44,$44,$44,$44,$44,$36,$8d
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$08
@song1ch0loop:
@ref20:
	.byte $82,$4a,$45,$3c,$3b,$36,$f1
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref21:
	.byte $82,$62,$5d,$54,$53,$4e,$f1
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref22:
	.byte $f9,$85
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref23:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref24:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$08
@song2ch0loop:
@ref25:
	.byte $80,$55,$4f,$55,$4e,$55,$54,$4f,$55,$4e,$81
@ref26:
	.byte $53,$4b,$53,$4a,$53,$52,$4b,$53,$4a,$81
@ref27:
	.byte $55,$4f,$55,$4e,$55,$54,$4f,$55,$4e,$81
	.byte $ff,$0a
	.word @ref26
@ref29:
	.byte $4f,$49,$4f,$48,$4f,$54,$4f,$55,$4e,$81
@ref30:
	.byte $53,$4b,$53,$4a,$59,$58,$53,$59,$52,$81
@ref31:
	.byte $4f,$49,$4f,$48,$55,$54,$4f,$55,$4e,$81
@ref32:
	.byte $53,$4b,$53,$4a,$53,$58,$53,$59,$52,$81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref33:
	.byte $9f
@ref34:
	.byte $9f
@ref35:
	.byte $9f
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
@ref40:
	.byte $9f
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref41:
	.byte $82,$3a,$3c,$3c,$3c,$3c,$3c,$3c,$3c,$3a,$3c,$3c,$3c,$3c,$3c,$3c
	.byte $3c
@ref42:
	.byte $30,$32,$32,$32,$32,$32,$32,$32,$30,$32,$32,$32,$32,$32,$32,$32
@ref43:
	.byte $3c,$40,$3c,$3c,$3c,$3c,$3c,$3c,$3a,$3c,$3c,$3c,$3c,$3c,$3c,$3c
	.byte $ff,$10
	.word @ref42
@ref45:
	.byte $3a,$3c,$3c,$3c,$3c,$3c,$3c,$3c,$3a,$3c,$3c,$3c,$3c,$3c,$3c,$3c
	.byte $ff,$10
	.word @ref42
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref42
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref49:
	.byte $9f
@ref50:
	.byte $9f
@ref51:
	.byte $9f
@ref52:
	.byte $9f
@ref53:
	.byte $9f
@ref54:
	.byte $9f
@ref55:
	.byte $9f
@ref56:
	.byte $9f
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref57:
	.byte $9f
@ref58:
	.byte $9f
@ref59:
	.byte $9f
@ref60:
	.byte $9f
@ref61:
	.byte $9f
@ref62:
	.byte $9f
@ref63:
	.byte $9f
@ref64:
	.byte $9f
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$08
@song3ch0loop:
@ref65:
	.byte $80,$3a,$38,$3a,$38,$3a,$38,$3a,$3c,$3a,$38,$3a,$38,$3a,$38,$36
	.byte $38
@ref66:
	.byte $3a,$38,$3a,$38,$3a,$38,$3a,$3c,$3a,$38,$3a,$38,$3a,$38,$36,$38
	.byte $ff,$10
	.word @ref66
@ref68:
	.byte $3a,$38,$3a,$38,$3a,$38,$3a,$3c,$3a,$38,$36,$38,$3a,$38,$36,$38
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref69:
	.byte $9f
@ref70:
	.byte $9f
@ref71:
	.byte $9f
@ref72:
	.byte $9f
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref73:
	.byte $9f
@ref74:
	.byte $9f
@ref75:
	.byte $9f
@ref76:
	.byte $9f
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref77:
	.byte $9f
@ref78:
	.byte $9f
@ref79:
	.byte $9f
@ref80:
	.byte $9f
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref81:
	.byte $9f
@ref82:
	.byte $9f
@ref83:
	.byte $9f
@ref84:
	.byte $9f
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref85:
	.byte $80,$2a,$8d,$28,$8d,$2a,$89,$28,$24,$28,$8d,$2a,$8d,$28,$8d,$2a
	.byte $89,$28,$24,$28,$8d
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref86:
	.byte $80,$3b,$37,$31,$33,$3b,$37,$31,$33,$3b,$37,$31,$33,$3b,$37,$31
	.byte $33,$3b,$37,$31,$33,$3b,$33,$31,$33,$3b,$37,$31,$33,$3b,$37,$31
	.byte $32,$81
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref87:
	.byte $f9,$85
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref88:
	.byte $f9,$85
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref89:
	.byte $f9,$85
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$0c
@song5ch0loop:
@ref90:
	.byte $82,$3c,$3c,$3a,$89,$3c,$3c,$3a,$89,$3c,$3c,$3b,$3c,$3c,$3b,$3c
	.byte $3c,$36,$89,$3a,$3a,$36,$89,$3a,$3a,$36,$89,$3a,$3a,$37,$36,$36
	.byte $3c,$3b,$36,$32,$89
@ref91:
	.byte $f9,$85
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref92:
	.byte $f9,$85
@ref93:
	.byte $f9,$85
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref94:
	.byte $87,$82,$29,$32,$89,$29,$32,$89,$29,$33,$35,$37,$29,$28,$89,$29
	.byte $36,$89,$29,$36,$89,$29,$2d,$31,$33,$29,$1a,$81
@ref95:
	.byte $f9,$85
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref96:
	.byte $f9,$85
@ref97:
	.byte $f9,$85
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref98:
	.byte $f9,$85
@ref99:
	.byte $f9,$85
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$06
@song6ch0loop:
@ref100:
	.byte $82,$3d,$37,$29,$30,$32,$87,$4a,$e5
@ref101:
	.byte $f9,$85
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@song6ch1loop:
@ref102:
	.byte $f9,$85
@ref103:
	.byte $f9,$85
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@song6ch2loop:
@ref104:
	.byte $82,$28,$8d,$32,$85,$1a,$e5
@ref105:
	.byte $f9,$85
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@song6ch3loop:
@ref106:
	.byte $f9,$85
@ref107:
	.byte $f9,$85
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@song6ch4loop:
@ref108:
	.byte $f9,$85
@ref109:
	.byte $f9,$85
	.byte $fd
	.word @song6ch4loop


@song7ch0:
	.byte $fb,$0e
@song7ch0loop:
@ref110:
	.byte $80,$37,$41,$45,$48,$91,$37,$45,$49,$4a,$91,$37,$41,$45,$48,$91
	.byte $37,$45,$49,$4a,$91
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@song7ch1loop:
@ref111:
	.byte $f9,$85
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@song7ch2loop:
@ref112:
	.byte $8b,$82,$41,$40,$40,$41,$40,$40,$40,$40,$40,$40,$40,$40,$40,$40
	.byte $45,$44,$44,$45,$44,$44,$44,$44,$44,$44,$44,$44,$44,$44,$41,$40
	.byte $40,$40,$40,$40,$40,$41,$40,$40,$40,$40,$40,$40,$45,$44,$44,$44
	.byte $44,$44,$44,$44,$81
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@song7ch3loop:
@ref113:
	.byte $f9,$85
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@song7ch4loop:
@ref114:
	.byte $f9,$85
	.byte $fd
	.word @song7ch4loop


@song8ch0:
	.byte $fb,$0e
@song8ch0loop:
@ref115:
	.byte $82,$33,$3a,$40,$3d,$3a,$36,$4a,$ed
@ref116:
	.byte $f9,$85
	.byte $fd
	.word @song8ch0loop

@song8ch1:
@song8ch1loop:
@ref117:
	.byte $f9,$85
@ref118:
	.byte $f9,$85
	.byte $fd
	.word @song8ch1loop

@song8ch2:
@song8ch2loop:
@ref119:
	.byte $82,$1a,$85,$24,$85,$32,$ed
@ref120:
	.byte $f9,$85
	.byte $fd
	.word @song8ch2loop

@song8ch3:
@song8ch3loop:
@ref121:
	.byte $f9,$85
@ref122:
	.byte $f9,$85
	.byte $fd
	.word @song8ch3loop

@song8ch4:
@song8ch4loop:
@ref123:
	.byte $f9,$85
@ref124:
	.byte $f9,$85
	.byte $fd
	.word @song8ch4loop


@song9ch0:
	.byte $fb,$08
@song9ch0loop:
@ref125:
	.byte $80,$37,$3b,$3f,$41,$3a,$37,$36,$3a,$40,$41,$3a,$37,$36,$3a,$3e
	.byte $45,$3e,$3b,$3a,$3e,$40,$45,$3e,$3b,$3a,$3a,$3e,$41,$3a,$37,$36
	.byte $3a,$3e,$41,$3a,$37,$36,$3a,$3e,$45,$3e,$3b,$3a,$3e,$40,$44,$81
	.byte $fd
	.word @song9ch0loop

@song9ch1:
@song9ch1loop:
@ref126:
	.byte $f9,$85
	.byte $fd
	.word @song9ch1loop

@song9ch2:
@song9ch2loop:
@ref127:
	.byte $8b,$82,$10,$10,$28,$10,$10,$10,$28,$10,$10,$10,$28,$10,$10,$10
	.byte $28,$10,$1a,$1a,$32,$1a,$1a,$1a,$32,$1a,$1a,$1a,$32,$1a,$1a,$1a
	.byte $32,$1a,$10,$10,$28,$10,$10,$10,$28,$10,$10,$10,$28,$10,$10,$10
	.byte $28,$10,$1a,$1a,$32,$1a,$1a,$1a,$32,$32,$1a,$1a
	.byte $fd
	.word @song9ch2loop

@song9ch3:
@song9ch3loop:
@ref128:
	.byte $f9,$85
	.byte $fd
	.word @song9ch3loop

@song9ch4:
@song9ch4loop:
@ref129:
	.byte $f9,$85
	.byte $fd
	.word @song9ch4loop


@song10ch0:
	.byte $fb,$08
@song10ch0loop:
@ref130:
	.byte $80,$4b,$4c,$4e,$87,$4b,$4c,$4f,$4e,$4c,$4e,$55,$53,$4f,$46,$91
	.byte $47,$48,$4a,$87,$47,$48,$4b,$4a,$48,$4a,$4f,$4f,$4b,$44,$91
@ref131:
	.byte $55,$56,$58,$87,$55,$56,$59,$5c,$59,$55,$56,$58,$87,$55,$56,$59
	.byte $5c,$59,$4a,$4b,$4c,$4e,$85,$4a,$4b,$4c,$4f,$5d,$54,$9d
	.byte $fd
	.word @song10ch0loop

@song10ch1:
@song10ch1loop:
@ref132:
	.byte $f9,$85
@ref133:
	.byte $f9,$85
	.byte $fd
	.word @song10ch1loop

@song10ch2:
@song10ch2loop:
@ref134:
	.byte $82,$3c,$83,$44,$83,$4b,$3c,$83,$44,$83,$4b,$4a,$83,$52,$83,$59
	.byte $4a,$83,$52,$83,$59,$4a,$83,$52,$83,$59,$4a,$83,$52,$83,$59,$3c
	.byte $83,$44,$83,$4b,$3c,$83,$44,$83,$4a,$81
@ref135:
	.byte $3c,$83,$44,$83,$4b,$3c,$83,$44,$83,$4b,$46,$83,$4e,$83,$55,$46
	.byte $83,$4e,$83,$55,$46,$83,$52,$83,$55,$4a,$83,$52,$83,$59,$3c,$83
	.byte $44,$83,$4b,$55,$4b,$4f,$52,$81
	.byte $fd
	.word @song10ch2loop

@song10ch3:
@song10ch3loop:
@ref136:
	.byte $f9,$85
@ref137:
	.byte $f9,$85
	.byte $fd
	.word @song10ch3loop

@song10ch4:
@song10ch4loop:
@ref138:
	.byte $f9,$85
@ref139:
	.byte $f9,$85
	.byte $fd
	.word @song10ch4loop


@song11ch0:
	.byte $fb,$06
@song11ch0loop:
@ref140:
	.byte $80,$4b,$4b,$4b,$44,$4b,$4b,$44,$4a,$44,$4a,$81
@ref141:
	.byte $49,$49,$49,$40,$49,$49,$40,$48,$40,$48,$81
@ref142:
	.byte $4b,$4b,$4b,$44,$4b,$4b,$44,$4a,$44,$4a,$81
	.byte $ff,$0b
	.word @ref141
	.byte $fd
	.word @song11ch0loop

@song11ch1:
@song11ch1loop:
@ref144:
	.byte $80,$3d,$3d,$3d,$36,$3d,$3d,$36,$3c,$36,$3c,$81
@ref145:
	.byte $3b,$3b,$3b,$32,$3b,$3b,$32,$3a,$32,$3a,$81
@ref146:
	.byte $3d,$3d,$3d,$36,$3d,$3d,$36,$3c,$36,$3c,$81
	.byte $ff,$0b
	.word @ref145
	.byte $fd
	.word @song11ch1loop

@song11ch2:
@song11ch2loop:
@ref148:
	.byte $80,$1e,$85,$24,$83,$36,$87,$29,$36,$81
@ref149:
	.byte $22,$85,$28,$83,$32,$87,$29,$32,$81
@ref150:
	.byte $1e,$85,$22,$83,$36,$87,$23,$36,$81
	.byte $ff,$09
	.word @ref149
	.byte $fd
	.word @song11ch2loop

@song11ch3:
@song11ch3loop:
@ref152:
	.byte $9f
@ref153:
	.byte $9f
@ref154:
	.byte $9f
@ref155:
	.byte $9f
	.byte $fd
	.word @song11ch3loop

@song11ch4:
@song11ch4loop:
@ref156:
	.byte $9f
@ref157:
	.byte $9f
@ref158:
	.byte $9f
@ref159:
	.byte $9f
	.byte $fd
	.word @song11ch4loop
